export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const SEARCH_DOGS_BY_NAME = "SEARCH_DOGS_BY_NAME";
export const ORDER = "ORDER";
export const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";
export const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
export const SELECT_TEMPERAMENT = "SELECT_TEMPERAMENT";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
